name: CI
on:
  pull_request:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Test user that signed Scala CLA
        id: cla_signed
        uses: ./
        with:
          author: Friendseeker

      - name: Test user that did not sign Scala CLA
        id: cla_not_signed
        uses: ./
        with:
          author: torvalds
        continue-on-error: true

      - name: Verify failure for non-signed user
        if: always()
        shell: bash
        run: |
          if [ "${{ steps.cla_not_signed.outcome }}" != "failure" ]; then
            echo "Error: The CLA check for 'torvalds' was expected to fail, but it did not."
            exit 1
          else
            echo "Success: The CLA check for 'torvalds' failed as expected."
          fi
      
